#!/usr/bin/env python3
"""Rasterize the official MiSans Regular into the device's Chinese/English fonts.

Download MiSans from https://hyperos.mi.com/font/zh/download/ and extract
MiSans/ttf/MiSans-Regular.ttf. Pass that file and lv_font_conv 1.5.3's JS entry.
The original font stays outside the repository; see docs/MiSans-LICENSE.txt.
"""

import argparse
import hashlib
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parents[1]
FONT_SHA256 = "9c120f0a849bc0aa5048daae2a3c0f6eecd828b5b33fce682a9622833f5feea6"
SIZES = (14, 16, 20, 24, 28, 32, 40, 48)


def characters():
    # Keep every GB2312 Han character, without its Greek, Cyrillic or kana.
    han = set()
    for lead in range(0xB0, 0xF8):
        for trail in range(0xA1, 0xFF):
            try:
                char = bytes((lead, trail)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if 0x4E00 <= ord(char) <= 0x9FFF:
                han.add(char)
    english = {chr(cp) for cp in range(0x20, 0x7F)}
    punctuation = set("°·—‘’“”…、。，！？：；（）【】《》〈〉「」『』〔〕￥　")
    punctuation.update(chr(cp) for cp in range(0xFF01, 0xFF5F))
    return english | punctuation, han


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font", type=Path)
    parser.add_argument("converter", type=Path)
    args = parser.parse_args()
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != FONT_SHA256:
        parser.error("MiSans Regular differs from the verified official source")
    english, han = characters()
    for size in SIZES:
        name = f"ui_font_misans_{size}"
        # Larger sizes serve English labels and the clock; Han text uses 16px.
        chars = english | han if size == 16 else english
        output = ROOT / "src" / f"{name}.c"
        command = ["node", str(args.converter), "--font", str(args.font),
                   "--size", str(size), "--bpp", "2" if size == 16 else "4",
                   "--no-compress", "--no-prefilter", "--no-kerning",
                   "--symbols", "".join(sorted(chars)), "--format", "lvgl",
                   "--lv-include", "lvgl.h", "--lv-font-name", name,
                   "-o", str(output)]
        subprocess.run(command, check=True, capture_output=True, text=True)
        source = output.read_text()
        # LVGL 8 treats FORMAT0 holes and end boundaries as real glyphs.
        # One sparse table gives exact lookups, including excluded languages.
        points = [int(cp, 16) for cp in re.findall(r'U\+([0-9A-Fa-f]+) "', source)]
        if points != sorted(map(ord, chars)):
            raise RuntimeError(f"{name}: converter omitted or reordered glyphs")
        start = source.index("static const", source.index("CHARACTER MAPPING"))
        end = source.index("};", source.index("static const lv_font_fmt_txt_cmap_t", start)) + 2
        offsets = [str(cp - points[0]) for cp in points]
        lines = ["    " + ", ".join(offsets[i:i + 16]) + ","
                 for i in range(0, len(offsets), 16)]
        mapping = "static const uint16_t unicode_list[] = {\n" + "\n".join(lines) + "\n};\n\n"
        mapping += ("static const lv_font_fmt_txt_cmap_t cmaps[] = {{\n"
                    f"    .range_start = {points[0]}, .range_length = {points[-1] - points[0] + 1},\n"
                    "    .glyph_id_start = 1, .unicode_list = unicode_list,\n"
                    f"    .glyph_id_ofs_list = NULL, .list_length = {len(points)},\n"
                    "    .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY\n}};")
        source = source[:start] + mapping + source[end:]
        source = re.sub(r"\.cmap_num = \d+", ".cmap_num = 1", source)
        # Do not embed machine-specific paths or the entire character set.
        source = source.replace(next(line for line in source.splitlines()
                                     if line.startswith(" * Opts:")),
                                " * MiSans Regular. Generated by tools/generate_misans_fonts.py.\n"
                                " * Copyright Xiaomi. See docs/MiSans-LICENSE.txt.")
        output.write_text(source.rstrip() + "\n")
        print(f"{name}: {len(chars)} characters")


if __name__ == "__main__":
    main()
